const styles: { [key: string]: React.CSSProperties } = {
  page: {
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#f4f4f9",
    color: "#333",
    minHeight: "100vh",
    padding: "4vw 2vw",
  },
  container: {
    maxWidth: "80vw",
    margin: "0 auto",
    background: "#ffffff",
    borderRadius: "10px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
    width: "100%",
  },
  header: {
    background: "rgb(130, 76, 175)",
    color: "#fff",
    padding: "4vw 2vw",
    textAlign: "center",
    fontSize: "clamp(1.5rem, 4vw, 2.5rem)",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(2vw, 1fr))",
    gap: "2vw",
    padding: "2vw",
  },
  hamburger: {
    position: "fixed",
    top: "20px",
    left: "20px",
    fontSize: "2rem",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    zIndex: 999,
  },

  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    height: "100vh",
    width: "100vw",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    zIndex: 1000,
  },

  sidebar: {
    position: "fixed",
    top: 0,
    left: 0,
    height: "100%",
    width: "250px",
    backgroundColor: "rgb(130, 76, 175)",
    transition: "transform 0.3s ease",
    zIndex: 1001,
    boxShadow: "2px 0 8px rgba(0,0,0,0.2)",
    overflowY: "auto",
  },

  sidebarContent: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    padding: "20px",
    paddingTop: "60px",
  },

  link: {
    color: "#fff",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: "10px 15px",
    borderRadius: "8px",
    textDecoration: "none",
    fontSize: "18px",
    transition: "background-color 0.3s ease, transform 0.2s ease",
    cursor: "pointer",
  },

  closeButton: {
    position: "absolute",
    top: "10px",
    right: "10px",
    background: "transparent",
    border: "none",
    color: "#fff",
    fontSize: "24px",
    cursor: "pointer",
    zIndex: 1002,
  },
  graphGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "20px",
    padding: "20px",
  },

  graphCard: {
    background: "#e6e6f0",
    borderRadius: "10px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    padding: "20px",
    textAlign: "center",
    transition: "transform 0.2s ease, background-color 0.2s ease",
    cursor: "pointer",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
    padding: "2rem",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
  },
  label: {
    marginBottom: "0.5rem",
    fontWeight: "600",
    color: "#444",
    fontSize: "1rem",
  },
  input: {
    padding: "0.75rem 1rem",
    fontSize: "1rem",
    borderRadius: "6px",
    border: "1px solid #ccc",
    outline: "none",
    transition: "border-color 0.2s ease",
  },
  inputFocus: {
    borderColor: "rgb(130, 76, 175)",
  },
  button: {
    padding: "0.75rem 1rem",
    fontSize: "1rem",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "rgb(130, 76, 175)",
    color: "#fff",
    fontWeight: "700",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
  },
  buttonHover: {
    backgroundColor: "rgb(110, 60, 155)",
  },
  errorText: {
    color: "red",
    marginTop: "1rem",
    fontWeight: "600",
  },
};
export default styles;
