# Usa la imagen base OpenJDK 17 con Alpine
FROM eclipse-temurin:17-jdk-alpine

ARG JAR_FILE=target/RoutineFights-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} /app.jar

COPY src/main/resources/application.properties /application.properties

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app.jar", "--spring.config.location=classpath:/application.properties"]
